name: PHPStan
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: "7.4"
        tools: phpstan
    - uses: "ramsey/composer-install@v1"
    - name: PHPStan
      run: phpstan analyse --configuration=phpstan.neon
