name: PHPUnit
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run:
    name: Build with ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["7.4", "8.0"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: ${{ matrix.php-versions }}
    - uses: "ramsey/composer-install@v1"
    - name: PHPUnit tests
      uses: php-actions/phpunit@v2
      with:
        php_version: ${{ matrix.php-versions }}
        configuration: phpunit.xml
